spring.application.name=firstproject
server.servlet.encoding.force=true

#h2 DB, \uC6F9 \uCF58\uC194 \uC811\uADFC \uD5C8\uC6A9
spring.h2.console.enabled=true

# 15\uAC15: data.sql \uC801\uC6A9\uC744 \uC704\uD55C \uC124\uC815(\uC2A4\uD504\uB9C1\uBD80\uD2B8 2.5 \uC774\uC0C1 \uD544\uC218)
spring.jpa.defer-datasource-initialization=true

# JPA \uB85C\uAE45 \uC124\uC815
logging.level.org.hibernate.SQL=DEBUG
# \uC774\uC058\uAC8C \uBCF4\uC5EC\uC8FC\uAE30
spring.jpa.properties.hibernate.format_sql=true
# \uD30C\uB77C\uBBF8\uD130 \uBCF4\uC5EC\uC8FC\uAE30
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# < DB URL \uACE0\uC815 \uC124\uC815 >
# 1. \uC720\uB2C8\uD06C URL \uC0DD\uC131 X => \uC11C\uBC84\uB97C \uC2E4\uD589\uD560\uB54C\uB9C8\uB2E4 \uB79C\uB364\uC73C\uB85C \uC0DD\uC131\uB418\uB294 jdbc url \uC8FC\uC18C \uC0DD\uC131 x
spring.datasource.generate-unique-name=false
# 2. \uACE0\uC815 url \uC124\uC815 => jdbc url \uC8FC\uC18C\uB97C \uACE0\uC815\uC73C\uB85C \uC124\uC815\uD568
spring.datasource.url=jdbc:h2:mem:testdb

# PostgreSQL \uC5F0\uB3D9
#spring.datasource.url=jdbc:postgresql://localhost:5432/firstproject_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.datasource.data=classpath:/data.sql
#spring.sql.init.mode=never
#spring.jpa.hibernate.ddl-auto=update